# Generated by Django 3.2.8 on 2021-11-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('geoLocation', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('service_date', models.DateTimeField()),
                ('service_publish_date', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.URLField(blank=True, null=True)),
                ('duration_credit', models.PositiveIntegerField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServicEventPool.location')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicEventPool.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('event_date', models.DateTimeField()),
                ('event_publish_date', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.URLField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, to='ServicEventPool.User')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServicEventPool.location')),
            ],
        ),
    ]
