# Generated by Django 3.2.8 on 2021-11-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('service_date', models.DateTimeField()),
                ('service_publish_date', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.URLField(blank=True, null=True)),
                ('duration_credit', models.PositiveIntegerField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServicEventPool.location')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicEventPool.user')),
            ],
        ),
    ]
