# Generated by Django 3.2.8 on 2021-12-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0003_auto_20211130_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
