# Generated by Django 3.2.8 on 2021-12-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagramURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedinURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilePictures/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitterURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
