# Generated by Django 3.2.8 on 2021-12-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0006_auto_20211211_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ServicEventPool/profilePictures/'),
        ),
    ]
