# Generated by Django 3.2.8 on 2021-12-13 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0010_auto_20211213_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ServicEventPool.location'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ServicEventPool.location'),
        ),
    ]
