# Generated by Django 3.2.8 on 2021-12-14 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServicEventPool', '0011_auto_20211213_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='applicants',
            field=models.ManyToManyField(blank=True, default='', related_name='user_event_applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, default='', related_name='user_event_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='applicants',
            field=models.ManyToManyField(blank=True, default='', related_name='user_service_applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='attendees',
            field=models.ManyToManyField(blank=True, default='', related_name='user_service_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_event_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_service_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
