# Generated by Django 3.2.8 on 2021-12-21 13:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0012_auto_20211214_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='pk', unique=True),
        ),
    ]
