# Generated by Django 3.2.8 on 2022-01-05 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServicEventPool', '0014_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='declinedList',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='user_event_declinedlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='declinedList',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='user_service_declinedlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='applicants',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='user_event_applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='user_event_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeCredit',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='applicants',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='user_service_applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='attendees',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='user_service_attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
