# Generated by Django 3.2.8 on 2022-01-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0016_profile_blockedcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
