# Generated by Django 3.2.8 on 2022-01-06 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServicEventPool', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1- Poor'), (2, '2- Fair'), (3, '3- Good'), (4, '4- Very Good'), (5, '5- Excellent')], default=3),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.PositiveIntegerField(choices=[(1, 'Open to Application'), (2, 'Closed to Application'), (3, 'Completed')], default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='service_status',
            field=models.PositiveIntegerField(choices=[(1, 'Open to Application'), (2, 'Closed to Application'), (3, 'Completed')], default=1),
        ),
        migrations.CreateModel(
            name='User_Service_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_service_status', models.PositiveIntegerField(choices=[(1, 'Applied'), (2, 'Accepted'), (3, 'Finished'), (4, 'Not Finished'), (5, 'Declined')])),
                ('service_serviceStatus', models.ManyToManyField(blank=True, default='', null=True, related_name='user_service_status_service', to='ServicEventPool.Service')),
                ('user_serviceStatus', models.ManyToManyField(blank=True, default='', null=True, related_name='user_service_status_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Event_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_event_status', models.PositiveIntegerField(choices=[(1, 'Applied'), (2, 'Accepted'), (3, 'Finished'), (4, 'Not Finished'), (5, 'Declined')])),
                ('event_eventStatus', models.ManyToManyField(blank=True, default='', null=True, related_name='user_event_status_event', to='ServicEventPool.Event')),
                ('user_eventStatus', models.ManyToManyField(blank=True, default='', null=True, related_name='user_event_status_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
