# Generated by Django 3.2.8 on 2022-01-06 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0018_auto_20220106_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ServicEventPool/images/eventPictures/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ServicEventPool/images/servicePictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blockedCredit',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ServicEventPool/images/profilePictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeCredit',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)]),
        ),
    ]
