# Generated by Django 3.2.8 on 2022-01-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0019_auto_20220106_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(),
        ),
    ]
