# Generated by Django 3.2.8 on 2022-01-07 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServicEventPool', '0020_auto_20220107_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_notifications', models.PositiveIntegerField(choices=[(1, 'Applied to Your Service'), (2, 'Applied to Your Event'), (3, 'Your application approved to Service'), (4, 'Your application approved to Event'), (5, 'Transaction is completed')])),
                ('event', models.ManyToManyField(blank=True, default='', null=True, related_name='event_notification', to='ServicEventPool.Event')),
                ('other_user', models.ManyToManyField(blank=True, default='', null=True, related_name='other_user_notification', to=settings.AUTH_USER_MODEL)),
                ('service', models.ManyToManyField(blank=True, default='', null=True, related_name='service_notification', to='ServicEventPool.Service')),
                ('user', models.ManyToManyField(blank=True, default='', null=True, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_activities', models.PositiveIntegerField(choices=[(1, 'Created a Service'), (2, 'Created an Event'), (3, 'Attended to Service'), (4, 'Attended to Event')])),
                ('event', models.ManyToManyField(blank=True, default='', null=True, related_name='event_activities', to='ServicEventPool.Event')),
                ('other_user', models.ManyToManyField(blank=True, default='', null=True, related_name='other_user_activities', to=settings.AUTH_USER_MODEL)),
                ('service', models.ManyToManyField(blank=True, default='', null=True, related_name='service_activities', to='ServicEventPool.Service')),
                ('user', models.ManyToManyField(blank=True, default='', null=True, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
