# Generated by Django 3.2.8 on 2022-01-07 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServicEventPool', '0021_activity_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='event',
        ),
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_activities', to='ServicEventPool.event'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='other_user',
        ),
        migrations.AddField(
            model_name='activity',
            name='other_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_user_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='service',
        ),
        migrations.AddField(
            model_name='activity',
            name='service',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_activities', to='ServicEventPool.service'),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_notification', to='ServicEventPool.event'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='other_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='other_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_user_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='service',
        ),
        migrations.AddField(
            model_name='notification',
            name='service',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_notification', to='ServicEventPool.service'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
