# Generated by Django 3.2.8 on 2022-01-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0022_auto_20220107_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='types_notifications',
            field=models.PositiveIntegerField(choices=[(1, 'Applied to Your Service'), (2, 'Applied to Your Event'), (3, 'Your application approved to Service'), (4, 'Your application approved to Event'), (5, 'Transaction is completed'), (6, 'Your application declined to Service'), (7, 'Your application declined to Event')]),
        ),
    ]
