# Generated by Django 3.2.8 on 2022-01-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicEventPool', '0023_auto_20220107_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('media_pic', models.ImageField(blank=True, null=True, upload_to='ServicEventPool/images/systemPictures/')),
            ],
        ),
    ]
