# Generated by Django 3.2.8 on 2022-01-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServicEventPool', '0026_auto_20220110_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_event_status',
            name='event_eventStatus',
        ),
        migrations.AddField(
            model_name='user_event_status',
            name='event_eventStatus',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_event_status_event', to='ServicEventPool.event'),
        ),
        migrations.RemoveField(
            model_name='user_event_status',
            name='user_eventStatus',
        ),
        migrations.AddField(
            model_name='user_event_status',
            name='user_eventStatus',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_event_status_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user_service_status',
            name='service_serviceStatus',
        ),
        migrations.AddField(
            model_name='user_service_status',
            name='service_serviceStatus',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_service_status_service', to='ServicEventPool.service'),
        ),
        migrations.RemoveField(
            model_name='user_service_status',
            name='user_serviceStatus',
        ),
        migrations.AddField(
            model_name='user_service_status',
            name='user_serviceStatus',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_service_status_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
